name: RDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Create User
      run: net user runneradmin Password@123

    - name: Add User to Admin
      run: net localgroup administrators runneradmin /add

    - name: Enable RDP
      run: |
        reg add "HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f

    - name: Download Ngrok
      run: |
        curl -Lo ngrok.zip https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip
        tar -xf ngrok.zip

    - name: Setup Ngrok
      run: |
        ngrok config add-authtoken $Env:NGROK_AUTH_TOKEN

    - name: Start Tunnel
      run: |
        start ngrok tcp 3389

    - name: Show Details
      run: |
        echo "Username: runneradmin"
        echo "Password: Password@123"
        curl http://127.0.0.1:4040/api/tunnels

    - name: Keep Alive
      run: ping -t localhost
