name: RDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Create User
      run: net user runneradmin Password@123

    - name: Enable RDP
      run: |
        net localgroup administrators runneradmin /add
        reg add "HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f

    - name: Stay Alive
      run: ping -t localhost
